# Generated by Django 4.2.30 on 2026-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockitem_cost_price_stockmovement_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
