# Generated by Django 4.2.30 on 2026-06-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_purchaseorder_is_approved_stockmovement_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='is_otc',
            field=models.BooleanField(default=False),
        ),
    ]
